name: somnio_firebase_authentication
description: Somnio's firebase authentication package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.0.1
  firebase_auth_web:
  google_sign_in: ^5.0.5
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  flutter_facebook_auth: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  build_runner: ^2.0.6


# The following section is specific to Flutter.
flutter:
